substitutions:
  device_name: riegoesp32001
  device_code: RIEGO_001
  # Opción B (simple): este token es el secreto que usa el ESP32 en la cabecera X-Device-Token.
  # Importante: la web NO lo genera; lo defines tú aquí y luego lo pegas en "Añadir dispositivo".
  # Debe tener 12+ caracteres y no puede ser CAMBIA_ESTE_TOKEN.
  device_token: !secret device_token

packages:
  base: !include riego_esp32_base.yaml
